[package]
name = "drumz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audio_thread_priority = "0.23.4"
rodio = "0.14.0"
midly = "0.5"
rand = "0.8.4"
rand_distr = "0.4.3"
